### ISSUE TITLE
`factor` overwrites the factor of other breakpoints

### ISSUE THREAD

**Issue by JeroenRoodIHS** [tgomilar/paroller.js#47]
When I apply paroller to an element and I'd like to have a default behavior/factor, I can't override that default with breakpoint-specific factors (e.g. `factorMd`, `factorXs`).

**Javascript:**
```javascript
$("#annoncer-screen").paroller({ factor: 0.3, factorMd: 0, type: 'foreground', direction: 'vertical' });
```

**SCSS:**
```scss
#annoncer-screen {
    width: 116.667vw;
    overflow: visible;
    z-index: 5;
    position: relative;
    left:8.333vw;
    img {
        width: 100%;
        transform: rotate(10deg);
        box-shadow: 0.5rem 4rem 4rem -1rem rgba(45, 62, 80, 0.6), 1rem 1rem 2.5rem 0rem rgba(0, 0, 0, 0.7);
    }
}
@media (min-width: 1024px) {
    #annoncer-screen {
        position: absolute;
        width: 1000px;
        left: 8.333vw;
    }
}
```

The breakpoint-specific values seem to work, as long as I do not set the 'default' `factor` value. In the code example above, `factorMd` seems to be overwritten or ignored when scrolling.
This seems to happen regardless of:
- Factor value (I tried 0, a positive value and a negative value)
- Positioning of the Paroller'd element (I've tried setting both to position: absolute, as well as the styling above)

Is this intended behavior? If so, how could I have a specific value for `factorMd`, which having a 'default' factor value for anything above that breakpoint?
